name = "my-online-store"
type = "javascript"

# Define routes for your functions
[env.production]
name = "samurai-heat-online-store"
route = "https://samurai-heat-online-store.pages.dev/*"
zone_id = "5785b34db93f51d881ad02cb105d0dd3"

[build]
command = "npm run build"
upload_format = "modules"

[[routes]]
pattern = "/api/create-checkout-session"
script = "create-checkout-session"

[[routes]]
pattern = "/api/fulfill-order"
script = "fulfill-order"